version: '2'
services:
  serverless-framework:
    build: .
    volumes:
      - ./serverless:/home/svrless
    ports:
      - 8000:8000
      - 3000:3000
      - 4000:3001
    command: tail -f /dev/null
